# Generated by Django 5.1.5 on 2025-02-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informasi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='siswa/'),
        ),
    ]
