# Generated by Django 5.1.6 on 2025-02-12 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informasi', '0002_siswa_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='nisn',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='NISN harus berupa angka', regex='^[0-9]*$')]),
        ),
    ]
